### ISSUE TITLE
I just realized there is a bug in the latest version of TCC

### ISSUE THREAD

**Issue by Videogamer555** [TinyCC/tinycc#11]
When using the latest version of TCC (0.9.27) to create a DLL file, you can no longer override the name of a function. You used to (in 0.9.26) be able to use __asm("function_name") to override it. For example. In my function definition:
```
__attribute((stdcall,dllexport)) int TestFunc(int arg){
	return arg;
}
```
the resulting DLL file has a function called _TestFunc@4 but that's not the desired result, so you add one more line of code to force it to have the name you want (which is just TestFunc). The line of code you need to add for that is this:
```
__attribute((stdcall,dllexport)) int TestFunc(int arg) __asm("TestFunc");
```
The resulting total code for this function is therefore:
```
__attribute((stdcall,dllexport)) int TestFunc(int arg) __asm("TestFunc");
__attribute((stdcall,dllexport)) int TestFunc(int arg){
	return arg;
}
```

This used to work in 0.9.26 but no longer works in 0.9.27. As of 0.9.27, the above code leaves the exported function still having the name _TestFunc@4 just as if the special name-setting code was never used.

Please fix this in your next version of TCC. I depend on this ability when creating DLL files, so that the names of the exported functions are reasonable names, not names with a bunch of extra symbols and numbers. Until this is fixed, I will need to downgrade to version 0.9.26.

**Comment by Videogamer555** [comment]
I just realized that the latest version of 0.9.27 isn't the same as 0.9.27 that's downloadable from http://download.savannah.gnu.org/releases/tinycc/ (which is itself linked to from the official TCC website https://bellard.org/tcc/ ). While both have the same version number, the one downloadable from here is like "revision 2" of the version, while the download on the official website is like "revision 1" of the version. The advantage to the download from the official download page is that it's already compiled so it can be used as-is without compiling. The disadvantage is it has some bugs like the ones pointed out in this issue I filed. The disadvantage of the one from Github is that there's no compiled copy of it anywhere on the internet, so anybody wanting to use it needs to compile it themselves.

After then I downloaded this one from this Github, and compiled it myself, and I found that the bug described in this issue I filed is no longer present. Therefore, since it is clear that this bug has already been corrected in the source code, I'm closing this issue.

**Comment by Videogamer555** [comment]
Here I've attached a copy of TCC that I compiled. It is compiled so 32bit is default (running tcc.exe compiles a 32bit EXE or DLL, so to compile a 64bit binary you need to run x86_64-win32-tcc.exe). This is the latest revision of TCC 0.9.27 as of me writing this comment.
[tcc-0.9.27-dev.zip](https://github.com/TinyCC/tinycc/files/3179973/tcc-0.9.27-dev.zip)

**Comment by Videogamer555** [comment]
By the way, as of the current revision (which you can download from the link in the above comment), not only is the bug fixed that this issue was about, there is also a new way to undecorate STDCALL functions. An attribute has been added that is called "nodecorate". Therefore, instead of something like this:
```
__attribute((stdcall,dllexport)) int TestFunc(int arg) __asm("TestFunc");
__attribute((stdcall,dllexport)) int TestFunc(int arg){
	return arg;
}
```

You can now do this:
```
__attribute((stdcall,dllexport,nodecorate)) int TestFunc(int arg){
	return arg;
}
```

And yes, the old way still works (now that the bug preventing it from working is gone), so this latest version won't break anybody's code that was written to be compiled in TCC 0.9.26. Prior to this 0.9.27 bug being fixed in the latest revision of 0.9.27, both the old 0.9.26 method (the __asm hack), and the new method 0.9.27 method (the nodecorate attribute) failed to work. Now that the bug is fixed, everything is working.

**Comment by wqweto** [comment]
Glad it worked!

Mind that commit 1dd6842654c8f8f6bf1a94364f0fd23ed10cc7e1 is not merged in the official [mob branch](https://repo.or.cz/tinycc.git/shortlog) yet.

**Comment by Videogamer555** [comment]
Who's responsible for merging it? And when is that planned to happen?
