### ISSUE TITLE
Where's the 2 utility programs that are supposed to come with TCC?

### ISSUE THREAD

**Issue by Videogamer555** [TinyCC/tinycc#12]
The problem is that I can't find any up-to-date versions of the tools that used to come with older versions of TCC. In TCC 0.9.26 there were tools to make DEF file and object archive file. These were called tiny_impdef.exe and tiny_libmaker.exe respectively. I don't know where to get the latest version of these tools. You need to be able to specify a DEF file corresponding to a DLL file in order to be able to use the DLL file in TCC. Without that, you can't call any functions in the DLL file, and not all DLL files are distributed with a corresponding DLL file. This means you need to be able to make your own DLL file. Please let me know if you plan to include those tools again in a future version at some point, or if they are now permanently removed from the TCC project.

**Comment by Videogamer555** [comment]
Ok, nevermind. It appears these are now built-in to TCC.

**Comment by wqweto** [comment]
This is a mirror repo and the issues are *not* monitored by people on the [dev mailing list](https://lists.nongnu.org/mailman/listinfo/tinycc-devel) that can help.

Be warned that most of your questions will remain unanswered here.
