### ISSUE TITLE
PowerPC support

### ISSUE THREAD

**Issue by neosaldina** [TinyCC/tinycc#14]
Is there any plan or branch that already had the support to generate the executable for PowerPC?

**Comment by arstero** [comment]
this is just for release
Here is the mailing list


tinycc-devel@nongnu.org<mailto:tinycc-devel@nongnu.org>


发自我的iPhone

在 2019年12月20日，下午4:44，neosaldina <notifications@github.com> 写道：

﻿

Is there any plan or branch that already had the support to generate the executable for PowerPC?

**Comment by neosaldina** [comment]
@arstero Thanks!
