### ISSUE TITLE
the mirror is not up-to-date?

### ISSUE THREAD

**Issue by wanjochan** [TinyCC/tinycc#6]
0.9.27 is out

**Comment by wqweto** [comment]
2018-08-15: synced w/ mob

**Comment by wanjochan** [comment]
@wqweto  Great, so is it manually synced?

**Comment by timotheecour** [comment]
indeed, looks like it; it's very misleading to call this a mirror when last update in this mirror (on mob branch) was from august 2018, whereas git://repo.or.cz/tinycc.git is getting updates as recent as 2020-04-07
